#title:            Aameer Rafiq Wani
#description:      My blog.
logo:             site-logo.png
disqus_shortname: aameergithubio
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
url:              http://aameer.github.io
domain_name:	  aameer.github.io

# Owner/author information
owner:
  name:           Aameer Rafiq Wani
  avatar:         bio-photo.jpg
  email:          aameer.rafiq@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:		AameerRafiqWani	
  facebook:		Aameer-Rafiq-Wani	
  github:		Aameer
  stackexchange:	http://stackoverflow.com/users/2833695/aameer
  linkedin:		aameerwani
  instagram:    aameer_rafiq
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:		

# Analytics and webmaster tools stuff goes here
google_analytics: UA-53756018-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Resume
    url: /resume.html
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
